"""Users and Roles

Revision ID: 95359d944c5b
Revises: 
Create Date: 2023-10-28 01:13:41.585950

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '95359d944c5b'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
