"""Users and accounts

Revision ID: a7d16e83ab75
Revises: f1da74f69a51
Create Date: 2023-10-28 01:37:30.741809

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a7d16e83ab75'
down_revision = 'f1da74f69a51'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
