"""Users and accounts

Revision ID: f1da74f69a51
Revises: d500e054f6fd
Create Date: 2023-10-28 01:36:57.455010

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f1da74f69a51'
down_revision = 'd500e054f6fd'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
